### ISSUE TITLE
Allow emoji over sent messages

### ISSUE THREAD

**Issue by miyoyo** [Pushjet/Pushjet-Android#7]
Currently, POSTing a message with emoji will show everything in the message that's before the emoji, maybe make it possible to use them in the future?

**Comment by Mechazawa** [comment]
That's odd. Unicode should work on the server side so this should be an issue with the app.

**Comment by miyoyo** [comment]
I Tested it with a remote linux VPS sending a request to the pushjet server and retrieving the data with a local windows PC, both systems using cURL.

The server stops registering after the emoji it seems...

![out](https://cloud.githubusercontent.com/assets/3525610/16173602/0f1fde06-35a7-11e6-9913-4d2589c329b1.png)
Re-sending it on pushjet server

**Comment by Mechazawa** [comment]
I just did a couple more tests on the server and it turns out unicode is 4 byte unicode not 3 byte. Thus my server kind of drops everything in the string as soon soon as it sees any. I'll be writing a fix soon.
Closing this issue in favor of the server side issue.

See https://github.com/Pushjet/Pushjet-Server-Api/issues/7
